const brands = [
    { brand: "2 BIZ", priceLevel: "Medel" },
    { brand: "365 Sunshine", priceLevel: "Medel" },
    { brand: "0pointzero", priceLevel: "Medel" },
    { brand: "Abeko", priceLevel: "Medel" },
    { brand: "Acne", priceLevel: "Exklusiv" },
    { brand: "Adam", priceLevel: "Låg" },
    { brand: "Adelsten", priceLevel: "Hög" },
    { brand: "Adidas", priceLevel: "Hög" },
    { brand: "Agent Provocateur", priceLevel: "Exklusiv" },
    { brand: "Alexander Wang", priceLevel: "Exklusiv" },
    { brand: "Alice Bizous", priceLevel: "Låg" },
    { brand: "Alpha industries", priceLevel: "Exklusiv" },
    { brand: "ALTEWAISAOME", priceLevel: "Exklusiv" },
    { brand: "American Apparel", priceLevel: "Hög" },
    { brand: "Amisu", priceLevel: "Låg" },
    { brand: "And other stories", priceLevel: "Exklusiv" },
    { brand: "Anerkjendt", priceLevel: "Hög" },
    { brand: "Anna Field", priceLevel: "Låg" },
    { brand: "April  7 7", priceLevel: "Medel" },
    { brand: "Armani", priceLevel: "Exklusiv" },
    { brand: "Asics", priceLevel: "Medel" },
    { brand: "Asos", priceLevel: "Låg" },
    { brand: "Atlant", priceLevel: "Låg" },
    { brand: "atmosphere", priceLevel: "Låg" },
    { brand: "B.Young", priceLevel: "Medel" },
    { brand: "Back (Ann-sofie Back)", priceLevel: "Hög" },
    { brand: "Balenciaga", priceLevel: "Exklusiv" },
    { brand: "Balmain", priceLevel: "Exklusiv" },
    { brand: "Banana Republic", priceLevel: "Hög" },
    { brand: "Barbour", priceLevel: "Exklusiv" },
    { brand: "Batistini", priceLevel: "Låg" },
    { brand: "Bayicon", priceLevel: "Medel" },
    { brand: "Ben Sherman", priceLevel: "Hög" },
    { brand: "Benneton", priceLevel: "Hög" },
    { brand: "Bergans", priceLevel: "Exklusiv" },
    { brand: "Bertoni", priceLevel: "Medel" },
    { brand: "Betty Barkley", priceLevel: "Medel" },
    { brand: "Bigarreau", priceLevel: "Hög" },
    { brand: "Bikbok", priceLevel: "Låg" },
    { brand: "Billabong", priceLevel: "Medel" },
    { brand: "Birger Mikkelsen", priceLevel: "Hög" },
    { brand: "Birkenstock", priceLevel: "Hög" },
    { brand: "Björn Borg", priceLevel: "Hög" },
    { brand: "Blend", priceLevel: "Medel" },
    { brand: "BLK Denim", priceLevel: "Medel" },
    { brand: "Blundstone", priceLevel: "Medel" },
    { brand: "Bläck", priceLevel: "Medel" },
    { brand: "Body flirt ", priceLevel: "Låg" },
    { brand: "Bon prix", priceLevel: "Låg" },
    { brand: "Bondelid", priceLevel: "Hög" },
    { brand: "Boohoo", priceLevel: "Låg" },
    { brand: "Boomerang", priceLevel: "Exklusiv" },
    { brand: "Boss", priceLevel: "Exklusiv" },
    { brand: "Boss, Hugo Boss", priceLevel: "Exklusiv" },
    { brand: "BRIXTOL", priceLevel: "Hög" },
    { brand: "Bruuns Bazar (BZR)", priceLevel: "Exklusiv" },
    { brand: "Bugatti", priceLevel: "Hög" },
    { brand: "Burberry", priceLevel: "Exklusiv" },
    { brand: "Burton", priceLevel: "Hög" },
    { brand: "Busnel", priceLevel: "Exklusiv" },
    { brand: "C.P. Company", priceLevel: "Hög" },
    { brand: "Cacharel", priceLevel: "Exklusiv" },
    { brand: "Calvin Klein", priceLevel: "Exklusiv" },
    { brand: "Canada Goose", priceLevel: "Exklusiv" },
    { brand: "Cantarana", priceLevel: "Låg" },
    { brand: "Cappuccini", priceLevel: "Medel" },
    { brand: "Capri", priceLevel: "Låg" },
    { brand: "Carhartt", priceLevel: "Hög" },
    { brand: "Carin Wester", priceLevel: "Medel" },
    { brand: "Caroline Rohmer", priceLevel: "Exklusiv" },
    { brand: "Casall", priceLevel: "Låg" },
    { brand: "Cecil", priceLevel: "Låg" },
    { brand: "cellbes", priceLevel: "Låg" },
    { brand: "Céline", priceLevel: "Exklusiv" },
    { brand: "Champion", priceLevel: "Medel" },
    { brand: "Chanel", priceLevel: "Exklusiv" },
    { brand: "Cheap Monday", priceLevel: "Medel" },
    { brand: "CK (Calvin Klein)", priceLevel: "Exklusiv" },
    { brand: "Claire DK", priceLevel: "Medel" },
    { brand: "Clarks", priceLevel: "Hög" },
    { brand: "Coast", priceLevel: "Medel" },
    { brand: "Columbia", priceLevel: "Medel" },
    { brand: "Container", priceLevel: "Medel" },
    { brand: "Converse (kläder)", priceLevel: "Låg" },
    { brand: "Converse (skor)", priceLevel: "Medel" },
    { brand: "COS", priceLevel: "Exklusiv" },
    { brand: "Craft", priceLevel: "Hög" },
    { brand: "Cream", priceLevel: "Hög" },
    { brand: "Crocker", priceLevel: "Medel" },
    { brand: "Crocs", priceLevel: "Medel" },
    { brand: "Cross", priceLevel: "Medel" },
    { brand: "Cubus", priceLevel: "Låg" },
    { brand: "Culture", priceLevel: "Hög" },
    { brand: "D Ahrling", priceLevel: "Hög" },
    { brand: "D&G Dolce i Gabbana", priceLevel: "Exklusiv" },
    { brand: "Dagmar", priceLevel: "Exklusiv" },
    { brand: "Daks", priceLevel: "Låg" },
    { brand: "Danwear", priceLevel: "Medel" },
    { brand: "Day by Birger Mikkelsen", priceLevel: "Exklusiv" },
    { brand: "Dea Axelsson", priceLevel: "Låg" },
    { brand: "Desigual", priceLevel: "Exklusiv" },
    { brand: "Detroit", priceLevel: "Låg" },
    { brand: "Diana Orving", priceLevel: "Hög" },
    { brand: "Dickies", priceLevel: "Medel" },
    { brand: "Didriksson", priceLevel: "Hög" },
    { brand: "Diesel", priceLevel: "Exklusiv" },
    { brand: "Dior", priceLevel: "Exklusiv" },
    { brand: "Divided", priceLevel: "Låg" },
    { brand: "DKNY", priceLevel: "Hög" },
    { brand: "Dobber", priceLevel: "Medel" },
    { brand: "Dolce & Gabbana", priceLevel: "Exklusiv" },
    { brand: "Donna Karan", priceLevel: "Exklusiv" },
    { brand: "Dr Denim", priceLevel: "Medel" },
    { brand: "Dr Martens", priceLevel: "Hög" },
    { brand: "Dressmann", priceLevel: "Låg" },
    { brand: "Dunderdon", priceLevel: "Medel" },
    { brand: "Ecco", priceLevel: "Medel" },
    { brand: "edc", priceLevel: "Medel" },
    { brand: "Edwin", priceLevel: "Exklusiv" },
    { brand: "Ellos", priceLevel: "Låg" },
    { brand: "Elvine", priceLevel: "Hög" },
    { brand: "Emilio", priceLevel: "Medel" },
    { brand: "Emilio cavallini", priceLevel: "Hög" },
    { brand: "Encore", priceLevel: "Hög" },
    { brand: "Esmara", priceLevel: "Låg" },
    { brand: "Esprit", priceLevel: "Medel" },
    { brand: "Etirel", priceLevel: "Låg" },
    { brand: "ETON", priceLevel: "Medel" },
    { brand: "Ewa i Walla", priceLevel: "Exklusiv" },
    { brand: "Everest", priceLevel: "Hög" },
    { brand: "FB sisters", priceLevel: "Låg" },
    { brand: "Fifth avenue shoe repair", priceLevel: "Hög" },
    { brand: "Filippa K", priceLevel: "Exklusiv" },
    { brand: "Five Seasons", priceLevel: "Hög" },
    { brand: "Fjällräven", priceLevel: "Hög" },
    { brand: "Flash woman", priceLevel: "Medel" },
    { brand: "Fornarina", priceLevel: "Exklusiv" },
    { brand: "Frank dandy", priceLevel: "Medel" },
    { brand: "Franklin & Marshall", priceLevel: "Hög" },
    { brand: "Fransa", priceLevel: "Medel" },
    { brand: "Fred Perry", priceLevel: "Hög" },
    { brand: "French Connection", priceLevel: "Exklusiv" },
    { brand: "frk.", priceLevel: "Medel" },
    { brand: "Galvin Green", priceLevel: "Hög" },
    { brand: "Gant", priceLevel: "Exklusiv" },
    { brand: "Gap", priceLevel: "Medel" },
    { brand: "Gerry Weber", priceLevel: "Exklusiv" },
    { brand: "Gina Tricot", priceLevel: "Låg" },
    { brand: "Givenchy", priceLevel: "Exklusiv" },
    { brand: "Gsus Industies", priceLevel: "Hög" },
    { brand: "Gram", priceLevel: "Hög" },
    { brand: "Graumann", priceLevel: "Hög" },
    { brand: "G-Star", priceLevel: "Hög" },
    { brand: "Gucci", priceLevel: "Exklusiv" },
    { brand: "Gudrun Sjödén", priceLevel: "Exklusiv" },
    { brand: "Guess", priceLevel: "Exklusiv" },
    { brand: "Gul & Blå", priceLevel: "Medel" },
    { brand: "Gunilla Pontén", priceLevel: "Medel" },
    { brand: "H&M", priceLevel: "Låg" },
    { brand: "Handberg", priceLevel: "Låg" },
    { brand: "H. Moser", priceLevel: "Hög" },
    { brand: "Haglöfs", priceLevel: "Hög" },
    { brand: "Hampton Republic", priceLevel: "Låg" },
    { brand: "Happy Heidemann", priceLevel: "Hög" },
    { brand: "Harris Tweed", priceLevel: "Exklusiv" },
    { brand: "Helly Hansen", priceLevel: "Hög" },
    { brand: "Helmut Lang", priceLevel: "Exklusiv" },
    { brand: "Henri Lloyd", priceLevel: "Exklusiv" },
    { brand: "Hermès ", priceLevel: "Exklusiv" },
    { brand: "Hilfiger Denim", priceLevel: "Hög" },
    { brand: "Holebrook", priceLevel: "Medel" },
    { brand: "Hollies", priceLevel: "Exklusiv" },
    { brand: "Hollister", priceLevel: "Medel" },
    { brand: "HOPE", priceLevel: "Exklusiv" },
    { brand: "House of Lola", priceLevel: "Hög" },
    { brand: "Hugin & Mumin", priceLevel: "Medel" },
    { brand: "Hugo Boss Black/Orange", priceLevel: "Exklusiv" },
    { brand: "Hummel", priceLevel: "Medel" },
    { brand: "Humör", priceLevel: "Medel" },
    { brand: "Hunkydory", priceLevel: "Exklusiv" },
    { brand: "ICHI", priceLevel: "Medel" },
    { brand: "Ida Sjöstedt", priceLevel: "Hög" },
    { brand: "I say", priceLevel: "Medel" },
    { brand: "Indigofera", priceLevel: "Exklusiv" },
    { brand: "Indiska", priceLevel: "Låg" },
    { brand: "InWear", priceLevel: "Hög" },
    { brand: "Isolde", priceLevel: "Låg" },
    { brand: "J.Lindeberg", priceLevel: "Hög" },
    { brand: "Jack and Jones", priceLevel: "Medel" },
    { brand: "Jackpot", priceLevel: "Medel" },
    { brand: "JC", priceLevel: "Medel" },
    { brand: "Jeane Blush", priceLevel: "Medel" },
    { brand: "Jenny Hellström", priceLevel: "Exklusiv" },
    { brand: "Jensen", priceLevel: "Hög" },
    { brand: "Jofama", priceLevel: "Hög" },
    { brand: "Joop!", priceLevel: "Exklusiv" },
    { brand: "Joseph Ribkoff", priceLevel: "Låg" },
    { brand: "JSFN", priceLevel: "Medel" },
    { brand: "Juicy Couture", priceLevel: "Exklusiv" },
    { brand: "Jumperfabriken", priceLevel: "Exklusiv" },
    { brand: "Just Cavalli", priceLevel: "Exklusiv" },
    { brand: "Kaffe", priceLevel: "Medel" },
    { brand: "Kappa", priceLevel: "Medel" },
    { brand: "Kappahl", priceLevel: "Låg" },
    { brand: "Karen Millen", priceLevel: "Hög" },
    { brand: "Kari Traa", priceLevel: "Låg" },
    { brand: "Kavat", priceLevel: "Exklusiv" },
    { brand: "KENZO", priceLevel: "Exklusiv" },
    { brand: "Killah", priceLevel: "Exklusiv" },
    { brand: "Kit Karnaby", priceLevel: "Hög" },
    { brand: "Kurt Kellerman", priceLevel: "Medel" },
    { brand: "KOOKAI", priceLevel: "Exklusiv" },
    { brand: "Koola Anna", priceLevel: "Medel" },
    { brand: "Kriss", priceLevel: "Exklusiv" },
    { brand: "La Redoute", priceLevel: "Låg" },
    { brand: "Lacoste", priceLevel: "Exklusiv" },
    { brand: "Lager 157", priceLevel: "Låg" },
    { brand: "Lambretta", priceLevel: "Hög" },
    { brand: "Lanvin", priceLevel: "Exklusiv" },
    { brand: "Laura Ashley", priceLevel: "Exklusiv" },
    { brand: "Laurel", priceLevel: "Hög" },
    { brand: "Laurie", priceLevel: "Medel" },
    { brand: "Le Coq Sportif", priceLevel: "Hög" },
    { brand: "Lee", priceLevel: "Hög" },
    { brand: "Lee 101", priceLevel: "Hög" },
    { brand: "Levi's", priceLevel: "Hög" },
    { brand: "Lexington", priceLevel: "Medel" },
    { brand: "Lindex", priceLevel: "Låg" },
    { brand: "Lipsy London", priceLevel: "Hög" },
    { brand: "LOGG", priceLevel: "Låg" },
    { brand: "Louis Vuitton", priceLevel: "Exklusiv" },
    { brand: "Lundhags", priceLevel: "Exklusiv" },
    { brand: "Lyle & Scott", priceLevel: "Exklusiv" },
    { brand: "Mac Scott", priceLevel: "Exklusiv" },
    { brand: "Mc Earl", priceLevel: "Låg" },
    { brand: "Machine", priceLevel: "Medel" },
    { brand: "Madison Avenue", priceLevel: "Låg" },
    { brand: "Maison Scotch", priceLevel: "Exklusiv" },
    { brand: "Malene Birger", priceLevel: "Exklusiv" },
    { brand: "Mama Licious", priceLevel: "Medel" },
    { brand: "Mango", priceLevel: "Medel" },
    { brand: "Marc by Marc jacobs", priceLevel: "Exklusiv" },
    { brand: "Marc Aurel", priceLevel: "Låg" },
    { brand: "Marc Jacobs", priceLevel: "Exklusiv" },
    { brand: "Marc Lauge", priceLevel: "Medel" },
    { brand: "Marc O'Polo", priceLevel: "Exklusiv" },
    { brand: "Marcs & Spencer", priceLevel: "Låg" },
    { brand: "Marimekko", priceLevel: "Exklusiv" },
    { brand: "Marie Philippe", priceLevel: "Hög" },
    { brand: "Marni", priceLevel: "Hög" },
    { brand: "Marwin", priceLevel: "Medel" },
    { brand: "Masai", priceLevel: "Exklusiv" },
    { brand: "Massimo Dutti", priceLevel: "Exklusiv" },
    { brand: "Mayla", priceLevel: "Hög" },
    { brand: "McKinley", priceLevel: "Låg" },
    { brand: "Melka", priceLevel: "Medel" },
    { brand: "Merrell", priceLevel: "Hög" },
    { brand: "Mexx", priceLevel: "Hög" },
    { brand: "Michael Kors", priceLevel: "Exklusiv" },
    { brand: "MIM", priceLevel: "Låg" },
    { brand: "Miss Sixty", priceLevel: "Hög" },
    { brand: "Missoni", priceLevel: "Exklusiv" },
    { brand: "Miu Miu", priceLevel: "Exklusiv" },
    { brand: "Modström", priceLevel: "Hög" },
    { brand: "Moncler", priceLevel: "Exklusiv" },
    { brand: "Mongul", priceLevel: "Hög" },
    { brand: "Monki", priceLevel: "Medel" },
    { brand: "MonRow", priceLevel: "Hög" },
    { brand: "Moondust", priceLevel: "Hög" },
    { brand: "Morris", priceLevel: "Exklusiv" },
    { brand: "Moschino", priceLevel: "Exklusiv" },
    { brand: "Mouli", priceLevel: "Medel" },
    { brand: "MTWTSS", priceLevel: "Medel" },
    { brand: "Mullberry", priceLevel: "Exklusiv" },
    { brand: "Munthe plus simonsen", priceLevel: "Exklusiv" },
    { brand: "My wear", priceLevel: "Låg" },
    { brand: "Neuw", priceLevel: "Hög" },
    { brand: "NA-KD", priceLevel: "Låg" },
    { brand: "Name it", priceLevel: "Låg" },
    { brand: "New Era", priceLevel: "Hög" },
    { brand: "Never denim", priceLevel: "Låg" },
    { brand: "Newline", priceLevel: "Medel" },
    { brand: "Newport", priceLevel: "Medel" },
    { brand: "Next", priceLevel: "Låg" },
    { brand: "Nike", priceLevel: "Medel" },
    { brand: "NN07", priceLevel: "Hög" },
    { brand: "NLY ONE", priceLevel: "Låg" },
    { brand: "Noa Noa", priceLevel: "Exklusiv" },
    { brand: "The north face", priceLevel: "Hög" },
    { brand: "Name it", priceLevel: "Låg" },
    { brand: "Nudie", priceLevel: "Hög" },
    { brand: "Oakley", priceLevel: "Hög" },
    { brand: "Objekt", priceLevel: "Medel" },
    { brand: "Oasis", priceLevel: "Medel" },
    { brand: "Odd Molly", priceLevel: "Exklusiv" },
    { brand: "Olé", priceLevel: "Låg" },
    { brand: "O'Neill", priceLevel: "Hög" },
    { brand: "One two", priceLevel: "Hög" },
    { brand: "Only", priceLevel: "Låg" },
    { brand: "On the road", priceLevel: "Medel" },
    { brand: "Original Penguin", priceLevel: "Hög" },
    { brand: "Orla Kiley", priceLevel: "Medel" },
    { brand: "Orsay", priceLevel: "Medel" },
    { brand: "Oscar Jacobsson", priceLevel: "Hög" },
    { brand: "Oxmo", priceLevel: "Hög" },
    { brand: "Paris Konfect", priceLevel: "Medel" },
    { brand: "Park Lane", priceLevel: "Hög" },
    { brand: "Part Two", priceLevel: "Hög" },
    { brand: "Pascal", priceLevel: "Medel" },
    { brand: "Patagonia", priceLevel: "Hög" },
    { brand: "Paul Frank", priceLevel: "Hög" },
    { brand: "Paul Smith", priceLevel: "Hög" },
    { brand: "Peak Performance", priceLevel: "Hög" },
    { brand: "Pepe Jeans", priceLevel: "Hög" },
    { brand: "Peppercorn", priceLevel: "Medel" },
    { brand: "Pier One", priceLevel: "Hög" },
    { brand: "Pierre Cardin", priceLevel: "Exklusiv" },
    { brand: "Point Zero", priceLevel: "Låg" },
    { brand: "Polarn & Pyret", priceLevel: "Hög" },
    { brand: "Polarn O. Pyret", priceLevel: "Hög" },
    { brand: "Polo jeans/Polo", priceLevel: "Exklusiv" },
    { brand: "Polo Ralph Lauren", priceLevel: "Exklusiv" },
    { brand: "Prada ", priceLevel: "Exklusiv" },
    { brand: "Pret à Porter", priceLevel: "Exklusiv" },
    { brand: "Proforma", priceLevel: "Låg" },
    { brand: "Pulz Jeans", priceLevel: "Hög" },
    { brand: "Puma", priceLevel: "Medel" },
    { brand: "Quiksilver", priceLevel: "Hög" },
    { brand: "Rabalder", priceLevel: "Hög" },
    { brand: "Rabens Saloner", priceLevel: "Exklusiv" },
    { brand: "Race Marine", priceLevel: "Låg" },
    { brand: "Rag and Bone", priceLevel: "Hög" },
    { brand: "Ralph Lauren", priceLevel: "Exklusiv" },
    { brand: "Ralston Design", priceLevel: "Exklusiv" },
    { brand: "Rappson", priceLevel: "Låg" },
    { brand: "Ray-Ban", priceLevel: "Exklusiv" },
    { brand: "Red Collar Projekt", priceLevel: "Hög" },
    { brand: "RedGreen", priceLevel: "Exklusiv" },
    { brand: "Reebok", priceLevel: "Hög" },
    { brand: "Remind Items", priceLevel: "Medel" },
    { brand: "Replay", priceLevel: "Exklusiv" },
    { brand: "Resteröds", priceLevel: "Hög" },
    { brand: "Riley", priceLevel: "Hög" },
    { brand: "Rip Curl", priceLevel: "Hög" },
    { brand: "River Island", priceLevel: "Medel" },
    { brand: "Roberto Cavalli", priceLevel: "Exklusiv" },
    { brand: "Rock n' Blue", priceLevel: "Hög" },
    { brand: "Rodebjer", priceLevel: "Exklusiv" },
    { brand: "Rosebud", priceLevel: "Medel" },
    { brand: "Rules by Mary", priceLevel: "Medel" },
    { brand: "Russell Athletic", priceLevel: "Hög" },
    { brand: "Rut m.fl.", priceLevel: "Medel" },
    { brand: "Rut & circle", priceLevel: "Medel" },
    { brand: "Rosemunde", priceLevel: "Hög" },
    { brand: "Röhnisch", priceLevel: "Medel" },
    { brand: "Sail Racing", priceLevel: "Medel" },
    { brand: "Saint James", priceLevel: "Exklusiv" },
    { brand: "Saint Michaels", priceLevel: "Låg" },
    { brand: "Saint Tropez", priceLevel: "Medel" },
    { brand: "Saints & Mortals", priceLevel: "Medel" },
    { brand: "Samsøe & Samsøe", priceLevel: "Exklusiv" },
    { brand: "Sand", priceLevel: "Exklusiv" },
    { brand: "Savane", priceLevel: "Exklusiv" },
    { brand: "Schott ", priceLevel: "Exklusiv" },
    { brand: "Second Female", priceLevel: "Hög" },
    { brand: "Selected Femme", priceLevel: "Medel" },
    { brand: "Selected Homme", priceLevel: "Medel" },
    { brand: "Serious Sally", priceLevel: "Låg" },
    { brand: "Skovhus", priceLevel: "Hög" },
    { brand: "Sisley", priceLevel: "Hög" },
    { brand: "Sisters", priceLevel: "Låg" },
    { brand: "Size 8 Needle", priceLevel: "Medel" },
    { brand: "Sheilay", priceLevel: "Låg" },
    { brand: "Skechers", priceLevel: "Medel" },
    { brand: "SMOG", priceLevel: "Medel" },
    { brand: "SNÖ of Sweden", priceLevel: "Hög" },
    { brand: "Soaked in Luxury", priceLevel: "Hög" },
    { brand: "Soc", priceLevel: "Låg" },
    { brand: "Soft Grey", priceLevel: "Låg" },
    { brand: "Solid", priceLevel: "Medel" },
    { brand: "Sonia Rykiel", priceLevel: "Exklusiv" },
    { brand: "Soul River", priceLevel: "Låg" },
    { brand: "Soyaconcept", priceLevel: "Hög" },
    { brand: "SS By SS", priceLevel: "Låg" },
    { brand: "Stradivarius", priceLevel: "Låg" },
    { brand: "Steilmann", priceLevel: "Exklusiv" },
    { brand: "Stella McCartney", priceLevel: "Exklusiv" },
    { brand: "Stenström", priceLevel: "Exklusiv" },
    { brand: "Stockholm, Stockholm LM", priceLevel: "Hög" },
    { brand: "Stormberg", priceLevel: "Medel" },
    { brand: "Street One", priceLevel: "Medel" },
    { brand: "Stylein", priceLevel: "Hög" },
    { brand: "Superdry", priceLevel: "Exklusiv" },
    { brand: "Supreme", priceLevel: "Exklusiv" },
    { brand: "Swedemount", priceLevel: "Medel" },
    { brand: "Sweet Sktbs", priceLevel: "Medel" },
    { brand: "Taifun", priceLevel: "Hög" },
    { brand: "Tamaris", priceLevel: "Hög" },
    { brand: "Ted Nicol", priceLevel: "Exklusiv" },
    { brand: "Tenson", priceLevel: "Medel" },
    { brand: "The Local Firm", priceLevel: "Medel" },
    { brand: "The North Face", priceLevel: "Exklusiv" },
    { brand: "The shirt factory", priceLevel: "Hög" },
    { brand: "These Glory Days", priceLevel: "Hög" },
    { brand: "TIGER, TIGER of Sweden", priceLevel: "Exklusiv" },
    { brand: "Timberland", priceLevel: "Hög" },
    { brand: "Tommy Hilfiger", priceLevel: "Exklusiv" },
    { brand: "Top Shop", priceLevel: "Låg" },
    { brand: "Topman", priceLevel: "Låg" },
    { brand: "Tretorn", priceLevel: "Hög" },
    { brand: "Twist & Tango", priceLevel: "Hög" },
    { brand: "Ulla Popken", priceLevel: "Exklusiv" },
    { brand: "Under Armour", priceLevel: "Medel" },
    { brand: "Uniforms for the Dedicated", priceLevel: "Hög" },
    { brand: "United colors of Benetton", priceLevel: "Hög" },
    { brand: "Urban Outfitters", priceLevel: "Hög" },
    { brand: "V Ave Shoe Repair", priceLevel: "Hög" },
    { brand: "Vagabond", priceLevel: "Hög" },
    { brand: "Vailent", priceLevel: "Hög" },
    { brand: "Warehouse", priceLevel: "Låg" },
    { brand: "Warp", priceLevel: "Medel" },
    { brand: "Weekday", priceLevel: "Medel" },
    { brand: "Velour", priceLevel: "Exklusiv" },
    { brand: "WERA", priceLevel: "Medel" },
    { brand: "Vero Moda", priceLevel: "Låg" },
    { brand: "WeSC", priceLevel: "Hög" },
    { brand: "Whyred", priceLevel: "Exklusiv" },
    { brand: "Vila", priceLevel: "Medel" },
    { brand: "Villervalla", priceLevel: "Hög" },
    { brand: "Viveca N.", priceLevel: "Låg" },
    { brand: "WINWIN", priceLevel: "Låg" },
    { brand: "Volcom", priceLevel: "Hög" },
    { brand: "Wolsey", priceLevel: "Hög" },
    { brand: "Wrangler", priceLevel: "Hög" },
    { brand: "XLNT", priceLevel: "Låg" },
    { brand: "Xueren", priceLevel: "Låg" },
    { brand: "XTI", priceLevel: "Medel" },
    { brand: "Yest", priceLevel: "Medel" },
    { brand: "Zara", priceLevel: "Medel" },
    { brand: "Zign", priceLevel: "Medel" },
    { brand: "Zoo York", priceLevel: "Hög" },
    { brand: "Zoul", priceLevel: "Medel" },
    { brand: "Åhlens", priceLevel: "Medel" },
    { brand: "Åhslind", priceLevel: "Medel" },
];

const data_barn = [
    { type: "T-shirt-lång ärm", low: 30, mid: 40, high: 50.0 },
    { type: "T-shirt-kort ärm", low: 20, mid: 30, high: 40.0 },
    { type: "Tjock tröja", low: 50, mid: 60, high: 70.0 },
    { type: "Body", low: 30, mid: 40, high: 50.0 },
    { type: "kjol/shorts", low: 30, mid: 40, high: 50.0 },
    { type: "Klänning", low: 50, mid: 70, high: 90.0 },
    { type: "Chinos", low: 40, mid: 50, high: 60.0 },
    { type: "Jeans", low: 50, mid: 60, high: 70.0 },
    { type: "Täckoverall", low: 80, mid: 100, high: 120.0 },
    { type: "Täckjacka", low: 60, mid: 80, high: 100.0 },
    { type: "Täckbyxor", low: 50, mid: 70, high: 90.0 },
    { type: "Mössor/Vantar", low: 20, mid: 30, high: 40.0 },
    { type: "Fleece/Del", low: 40, mid: 60, high: 80.0 },
    { type: "Vinterskor/Stövlar", low: 60, mid: 60, high: 60.0 },
    { type: "Gummistövlar", low: 40, mid: 40, high: nan },
    { type: "Gymnastik/Lågskor", low: 40, mid: 40, high: 40.0 },
    { type: "Tygskor/Sandaler", low: 30, mid: 30, high: 30.0 },
];

const data_dam = [
    { type: "T-shirt-kort ärm", low: 40, mid: 60.0, high: 80.0 },
    { type: "T-shirt-lång ärm", low: 50, mid: 70.0, high: 90.0 },
    { type: "Tunn stickad Tröja", low: 70, mid: 90.0, high: 120.0 },
    { type: "Tjock stickad tröja", low: 80, mid: 100.0, high: 160.0 },
    { type: "Skjorta", low: 80, mid: 90.0, high: 100.0 },
    { type: "Blus", low: 50, mid: 70.0, high: 90.0 },
    { type: "Tunika", low: 70, mid: 90.0, high: 120.0 },
    { type: "Kjol/Shorts", low: 50, mid: 70.0, high: 90.0 },
    { type: "2-Delad dress", low: 100, mid: 120.0, high: 140.0 },
    { type: "Baddräkt/Bikini", low: 50, mid: nan, high: nan },
    { type: "Shorts", low: 50, mid: 70.0, high: 90.0 },
    { type: "Klänning", low: 80, mid: 100.0, high: 150.0 },
    { type: "Jeans", low: 80, mid: 100.0, high: 120.0 },
    { type: "Byxa", low: 70, mid: 90.0, high: 110.0 },
    { type: "Höst/Vår jacka", low: 120, mid: 180.0, high: 250.0 },
    { type: "Skinnjacka", low: 150, mid: 250.0, high: 350.0 },
    { type: "Täckjacka", low: 130, mid: 230.0, high: 330.0 },
    { type: "Täckväst", low: 80, mid: 90.0, high: 150.0 },
    { type: "Täckbyxa", low: 70, mid: 90.0, high: 120.0 },
    { type: "Kappa", low: 100, mid: 150.0, high: 250.0 },
    { type: "Vinterskor/Stövlar", low: 120, mid: 120.0, high: 120.0 },
    { type: "Gummistövlar", low: 70, mid: 70.0, high: 70.0 },
    { type: "Gymnastik/Lågskor", low: 70, mid: 70.0, high: 70.0 },
    { type: "Tygskor/Sandaler", low: 50, mid: 50.0, high: 50.0 },
];

const data_herr = [
    { type: "T-shirt", low: 30, mid: 40, high: 60 },
    { type: "T-shirt-lång ärm", low: 50, mid: 70, high: 90 },
    { type: "Piké", low: 40, mid: 50, high: 60 },
    { type: "Tunn stickad Tröja", low: 70, mid: 90, high: 120 },
    { type: "Tjock stickad tröja", low: 80, mid: 100, high: 160 },
    { type: "Hoodie", low: 60, mid: 80, high: 100 },
    { type: "Jeansskjorta", low: 80, mid: 120, high: 150 },
    { type: "Skjorta", low: 80, mid: 90, high: 100 },
    { type: "Hel kostym", low: 200, mid: 200, high: 200 },
    { type: "Kavaj", low: 130, mid: 130, high: 130 },
    { type: "Kostymbyxa", low: 70, mid: 70, high: 70 },
    { type: "Kostymväst", low: 50, mid: 50, high: 50 },
    { type: "Chinos", low: 60, mid: 80, high: 100 },
    { type: "Shorts", low: 50, mid: 70, high: 90 },
    { type: "Badbyxor", low: 50, mid: 50, high: 50 },
    { type: "Jeans", low: 80, mid: 100, high: 160 },
    { type: "Höst/Vår jacka", low: 120, mid: 180, high: 250 },
    { type: "Skinnjacka", low: 150, mid: 250, high: 350 },
    { type: "Täckjacka", low: 130, mid: 230, high: 330 },
    { type: "Täckväst", low: 80, mid: 90, high: 150 },
    { type: "Täckbyxa", low: 70, mid: 90, high: 120 },
    { type: "Överrock", low: 100, mid: 150, high: 250 },
    { type: "Jeansjacka", low: 90, mid: 150, high: 250 },
    { type: "Vinterskor/Stövlar", low: 120, mid: 120, high: 120 },
    { type: "Gummistövlar", low: 70, mid: 70, high: 70 },
    { type: "Gymnastik/Lågskor", low: 70, mid: 70, high: 70 },
    { type: "Tygskor/Sandaler", low: 50, mid: 50, high: 50 },
];

const data_sport = [
    { type: "Zipjacka", low: 60, mid: 80, high: 100 },
    { type: "Tröja-lång ärm", low: 50, mid: 70, high: 90 },
    { type: "Tröja-Kort ärm", low: 40, mid: 60, high: 80 },
    { type: "Korta tights", low: 50, mid: 70, high: 90 },
    { type: "Tights", low: 60, mid: 80, high: 100 },
    { type: "Överdragsbyxor", low: 60, mid: 80, high: 100 },
    { type: "Mjukbyxor", low: 50, mid: 70, high: 90 },
    { type: "Skaljackor", low: 100, mid: 140, high: 200 },
];

export { brands, data_barn, data_dam, data_herr, data_sport };
